import type { Iteration } from "./state.ts";
import type { LintPass, TestRun, Verification } from "./verification.ts";

export const reviewHeading = "## Review in 2 minutes";

export type ProposalInput = { iteration: Iteration; verification: Verification; title: string; summary: string; mode: "dry-run" | "draft" };

export function renderPullRequest({ iteration, verification, title, summary, mode }: ProposalInput): string {
  const { target, answer, base } = iteration;
  return [
    `# ${title}`,
    "",
    summary.trim(),
    "",
    "## Why this module",
    "",
    `\`${target.module}\` ranks #${target.rank} in \`${iteration.scope}\` with a coherence target score of ${(100 * target.score).toFixed(2)} (pressure × pain × safety).`,
    "",
    `Recommendation: ${target.reason}`,
    ...(target.evidence.length > 0 ? ["", "Evidence:", "", ...target.evidence.map((item) => `- ${item}`)] : []),
    ...(answer === null ? [] : ["", `Human answer from [#${answer.number}](${answer.url}): ${answer.answer}`]),
    "",
    "## Step and verification class",
    "",
    `Step: **${target.step}**. Verification class: **${target.verification}**.`,
    "",
    `## Coherence Index for \`${verification.index.scope}\``,
    "",
    "| Dimension | Before | After | Change |",
    "| --- | ---: | ---: | ---: |",
    indexRow("composite", verification.index.composite),
    ...Object.entries(verification.index.dimensions).map(([dimension, change]) => indexRow(dimension, change, verification.index.targeted.some((targeted) => targeted === dimension))),
    "",
    "Targeted dimensions are in bold; none of them may drop.",
    "",
    "## Checks",
    "",
    `- Changed: ${verification.changes.files.length} files, +${verification.changes.added} −${verification.changes.deleted} (${verification.changes.lines} of ${verification.changes.maxLines} lines; renamed files count only their edits).`,
    `- Lint: ${lintLine(verification.lint)}`,
    ...testLines(verification.tests),
    `- Files in active pull requests: ${verification.busyFilesTouched.length === 0 ? "untouched" : verification.busyFilesTouched.join(", ")}.`,
    "",
    "---",
    "",
    `Generated by the coherence loop (${mode}) from \`${base.ref}\` at ${base.commit.slice(0, 12)}.`,
    "",
  ].join("\n");
}

function indexRow(name: string, { before, after }: { before: number | null; after: number | null }, targeted = false): string {
  const label = targeted ? `**${name}**` : name;
  const change = before === null || after === null ? "n/a" : `${after - before >= 0 ? "+" : ""}${(after - before).toFixed(2)}`;
  return `| ${label} | ${before?.toFixed(2) ?? "n/a"} | ${after?.toFixed(2) ?? "n/a"} | ${change} |`;
}

function lintLine(lint: LintPass): string {
  if (lint.status === "not run") return `not run: ${lint.reason}.`;
  return `ruff and oxlint find ${lint.after} findings in the ${lint.files} touched source files, ${lint.before} before.`;
}

function testLines(tests: TestRun[]): string[] {
  if (tests.length === 0) return ["- Tests: no test touches or imports the changed files."];
  return tests.map(({ runner, files, status, reason }) => `- ${runner} on ${files.map((file) => `\`${file}\``).join(", ")}: ${status === "not run" ? `not run locally: ${reason}` : status}.`);
}
