import type { ArchitecturePayload, ModuleKind } from "../src/architecture/contracts/index.ts";
import { listBlobs, readBlobs } from "../src/architecture/index/git.ts";

export type ScopeFile = { path: string; sha: string; original: string; text: string; lines: number; generatedLines: number };

export type Scope = {
  path: string;
  production: ScopeFile[];
  tests: ScopeFile[];
  excluded: string[];
  isMeasured(path: string): boolean;
  isWithin(path: string): boolean;
};

const unmeasuredKinds = new Set<ModuleKind>(["migrations", "generated"]);
const measuredSource = /\.(py|tsx?)$/;
const generatedMarker = /^(?:\/\/|#)\s*(?:Generated by\b|@generated\b)/;
const blockOpener = /[{([]\s*$/;
const blockCloser = /^[})\]]/;

export async function readScope(root: string, payload: ArchitecturePayload, path: string): Promise<Scope> {
  const isWithin = (file: string) => path === "." || file.startsWith(`${path}/`);
  const unmeasured = unmeasuredModules(payload);
  const inScope = payload.files.filter(([file]) => isWithin(file) && measuredSource.test(file));
  const generated = inScope.filter(([, module]) => unmeasured[module]).map(([file]) => file);
  const kept = inScope.filter(([, module]) => !unmeasured[module]);
  const shas = new Map((await listBlobs(root, payload.tree)).map(({ path: file, sha }) => [file, sha]));
  const texts = await readBlobs(root, kept.map(([file]) => shas.get(file)!));
  const scopeFile = (file: string): ScopeFile => {
    const sha = shas.get(file)!;
    const original = texts.get(sha) ?? "";
    const text = withoutGeneratedRegions(original);
    const lines = nonBlankLines(text);
    return { path: file, sha, original, text, lines, generatedLines: nonBlankLines(original) - lines };
  };
  const filesWithRole = (role: string) => kept.filter(([, , , fileRole]) => fileRole === role).map(([file]) => scopeFile(file));
  const [production, empty] = partition(filesWithRole("production"), ({ lines }) => lines > 0);
  if (production.length === 0) throw new Error(`${path} holds no production .py, .ts, or .tsx code outside migrations and generated modules at ${payload.commit ?? payload.tree}.`);
  const measured = new Set(production.map(({ path: file }) => file));
  return {
    path,
    production,
    tests: filesWithRole("test"),
    excluded: [...generated, ...empty.map(({ path: file }) => file)].sort(),
    isMeasured: (file) => measured.has(file),
    isWithin,
  };
}

export function unmeasuredModules(payload: ArchitecturePayload): Uint8Array {
  const isUnmeasured = (module: number) => moduleChain(payload, module).some((ancestor) => unmeasuredKinds.has(payload.modules[ancestor]![3]));
  return Uint8Array.from(payload.modules, (_, module) => Number(isUnmeasured(module)));
}

export function moduleChain(payload: ArchitecturePayload, module: number): number[] {
  const chain: number[] = [];
  for (let current = module; current !== -1; current = payload.modules[current]![2]) chain.push(current);
  return chain;
}

function withoutGeneratedRegions(text: string): string {
  const lines = text.split("\n");
  lines.forEach((line, index) => {
    if (generatedMarker.test(line)) lines.fill("", index, generatedRegionEnd(lines, index) + 1);
  });
  return lines.join("\n");
}

function generatedRegionEnd(lines: string[], marker: number): number {
  const declaration = marker + 1;
  if (declaration >= lines.length || !blockOpener.test(lines[declaration]!)) return Math.min(declaration, lines.length - 1);
  const closer = lines.findIndex((line, index) => index > declaration && blockCloser.test(line));
  return closer === -1 ? declaration : closer;
}

export function nonBlankLines(text: string): number {
  return text.split("\n").filter((line) => line.trim() !== "").length;
}

export function totalLines(files: ScopeFile[]): number {
  return files.reduce((total, { lines }) => total + lines, 0);
}

function partition<T>(items: T[], keeps: (item: T) => boolean): [T[], T[]] {
  return [items.filter(keeps), items.filter((item) => !keeps(item))];
}
